### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by ghost** [supersmartypants/BoostedBrightness#47]
When is the 1.20.2 version available?

![image](https://github.com/adamviola/BoostedBrightness/assets/113762450/897c3d31-4ac6-4b38-bea3-90984ee5604e)

**Comment by osfanbuff63** [comment]
The 1.20.1 version works on 1.20.2.

**Comment by NotRyken** [comment]
> The 1.20.1 version works on 1.20.2.

Partially, but Minecraft will crash with a `NoSuchMethodError` if you attempt to open the ModMenu screen.

**Comment by R00tB33rMan** [comment]
> > The 1.20.1 version works on 1.20.2.
> 
> Partially, but Minecraft will crash with a `NoSuchMethodError` if you attempt to open the ModMenu screen.

Newest branch fixes 1.20.2 compatibility but it appears the menu crash recurs on 1.20.3-4 with and without your changes. Thought I should mention this, in case this helps.

**Comment by NotRyken** [comment]
Yeah, that's to be expected.
